### ISSUE TITLE
Somewhere after 3.1.1. Cyrillic characters in defaultValue or labels leads to node-fetch TypeError

### ISSUE THREAD

**Issue by neoromantic** [appbaseio/reactivesearch#1408]
**Affected Projects** React

**Library Version:** 3.7.9

**Describe the bug**
After update to latest version from one we used before (3.1.1) Reactive search fails with TypeError regarding contents of a res headers. 

The issue is that we have some Cyrillic characters in our filters and when Reactivesearch tries to set HTTP header with it, node-fetch checks it for invalid symbols and crashes.

As far as I understand, the issue can be fixed by running data through through encodeURI.

**To Reproduce**
Steps to reproduce the behavior (we have it like this):

```
<SingleList {...specProps} render={specRenderItem} />
```

```
const specProps = {
  componentId: "SpecFilter",
  dataField: "about.professional.specializations.typeName.keyword",
  selectAllLabel: "все специальности",
  defaultValue: "все специальности"
x};
```

If you have Cyrillic characters like we do, you'll encounter this error. 

**Expected behavior**
We should get a results from AppBase and no exceptions.

**Additional context**

Here's stack trace:

```
TypeError: {"SpecFilter":{"dataField":"about.professional.specializations.typeName.keyword","showSearch":false,"size":100,"showCount":false,"selectAllLabel":"все специальности","defaultValue":"все специальности","placeholder":"Search","showFilter":true,"showRadio":true,"sortBy":"count","showMissing":false,"missingLabel":"N/A","showLoadMore":false,"loadMoreLabel":"Load More","componentType":"SINGLELIST","react":{"and":"SpecFilter__internal"}},"SpecFilter__internal":{"dataField":"about.professional.specializations.typeName.keyword","showSearch":false,"size":100,"showCount":false,"selectAllLabel":"все специальности","defaultValue":"все специальности","placeholder":"Search","showFilter":true,"showRadio":true,"sortBy":"count","showMissing":false,"missingLabel":"N/A","showLoadMore":false,"loadMoreLabel":"Load More","componentType":"SINGLELIST"}} is not a legal HTTP header value
    at validateValue (/Users/sergeypetrov/dev/artists/node_modules/@appbaseio/reactivesearch/node_modules/node-fetch/lib/index.js:677:9)
    at Headers.append (/Users/sergeypetrov/dev/artists/node_modules/@appbaseio/reactivesearch/node_modules/node-fetch/lib/index.js:831:3)
    at new Headers (/Users/sergeypetrov/dev/artists/node_modules/@appbaseio/reactivesearch/node_modules/node-fetch/lib/index.js:756:11)
    at new Request (/Users/sergeypetrov/dev/artists/node_modules/@appbaseio/reactivesearch/node_modules/node-fetch/lib/index.js:1201:19)
    at /Users/sergeypetrov/dev/artists/node_modules/@appbaseio/reactivesearch/node_modules/node-fetch/lib/index.js:1369:19
    at new Promise (<anonymous>)
    at fetch (/Users/sergeypetrov/dev/artists/node_modules/@appbaseio/reactivesearch/node_modules/node-fetch/lib/index.js:1367:9)
    at fetch (/Users/sergeypetrov/dev/artists/node_modules/@appbaseio/reactivesearch/node_modules/cross-fetch/dist/node-ponyfill.js:10:20)
    at /Users/sergeypetrov/dev/artists/node_modules/@appbaseio/reactivesearch/node_modules/appbase-js/dist/appbase-js.cjs.js:271:16
    at runMicrotasks (<anonymous>)
```

**Comment by siddharthlatest** [comment]
Hey @neoromantic, is it possible to share a code sandbox demonstrating this issue?
