### ISSUE TITLE
Cannot customize defaultQuery in Typescript

### ISSUE THREAD

**Issue by stonesthatwhisper** [appbaseio/reactivesearch#1438]
**Affected Projects**
React Web

**Library Version:** x.y.z
 "@appbaseio/reactivesearch": "^3.5.0-beta.3",
 "typescript": "3.6.3"

**Describe the bug**
It's not possible to customize `defaultQuery` of `SingleDropdownList` in Typescript, getting a error when browsing to the page:
```
TypeError: props.setDefaultQuery is not a function
    at updateDefaultQuery (/app/node_modules/appbaseio/reactivecore/lib/utils/helper.js:1:2246
    at updateInternalQuery (/app/node_modules/appbaseio/reactivecore/lib/utils/helper.js:1:11953
    at SingleDropdownList.updateDefaultQuery (/app/node_modules/appbaseio/reactivesearch/lib/components/list/SingleDropdownList.js:375:35
    at SingleDropdownList.updateQueryOptions (/app/node_modules/appbaseio/reactivesearch/lib/components/list/SingleDropdownList.js:390:11
    at new SingleDropdownList (/app/node_modules/appbaseio/reactivesearch/lib/components/list/SingleDropdownList.js:83:9
```

**To Reproduce**
```
  <SingleDropdownList
        dataField="type"
        defaultQuery={(value, props) => {
              console.log(value, props);
              return {};
        }}
/>

**Expected behavior**
Customizing the defaultQuery in Typescript would work.

**Comment by stonesthatwhisper** [comment]
`@appbaseio/reactivesearch@3.8.0` seems to have no issue, close this.
