### ISSUE TITLE
Latest Vue Cli breaking 

### ISSUE THREAD

**Issue by dominicpedro** [appbaseio/reactivesearch#1915]
Hi

My team upgraded our vue project to the latest vue cli, and started seeing an error regarding the range slider component.
we experienced the following error:

﻿
Uncaught ReferenceError: process is not defined
    at getComponents (ssr-a41dfea9.js:20:1)
    at Module../node_modules/@appbaseio/reactivesearch-vue/dist/es/RangeSlider.js (RangeSlider.js:25:28)
   

and were able to trace it to this line of code

https://github.com/appbaseio/reactivesearch/blob/13a29bab1db06f9ccf5964c625f693bc106baba0/packages/vue/src/components/range/addons/ssr.js#L10

We found a workaround through vue.config, but adding the following lines:

`const webpack = require('webpack');` at the top of the file

`plugins: [ new webpack.ProvidePlugin({process: 'process',  }) ]` added to configureWebpack

Wer'e not sure why this ssr related code is affecting us as we don't actually use nuxt or any other ssr setup, so think it may just be a result of the upgrade to vue cli and possibly its use of webpack 5..

Hopefully you can find a solution that doesn't require the change to the vue config

Thanks

**Comment by dominicpedro** [comment]
apparently its related to this : https://stackoverflow.com/questions/65018431/webpack-5-uncaught-referenceerror-process-is-not-defined.

**Comment by AcckiyGerman** [comment]
Hello, I follow the [quick start guide](https://docs.appbase.io/docs/reactivesearch/vue/overview/QuickStart/) and get the same bug.

To bootstrap the project I use `npm init vue@2` which uses **[vitejs](https://vitejs.dev/)** instead of **webpack**.

Thus the [solution for webpack users](https://stackoverflow.com/a/65018686/7709003) does not help.

Update:
This [vitejs workaround](https://github.com/vitejs/vite/issues/1973#issuecomment-815695512) helped.

### The bug is a blocker for new Users therefore requires a general solution.
