### ISSUE TITLE
Failed prop type: ToggleButton: prop type `enableAppbase` is invalid; it must be a function, usually from the `prop-types` package, but received `undefined`

### ISSUE THREAD

**Issue by stonesthatwhisper** [appbaseio/reactivesearch#2082]
**Affected Projects**

React

**Library Version:** x.y.z
"@appbaseio/reactivesearch": "3.40.2",

**Describe the bug**
```
Warning: Failed prop type: ToggleButton: prop type `enableAppbase` is invalid; it must be a function, usually from the `prop-types` package, but received `undefined`.This often happens because of typos such as `PropTypes.function` instead of `PropTypes.func`.
    at ToggleButton (webpack-internal:///./node_modules/@appbaseio/reactivesearch/lib/components/list/ToggleButton.js:62:3)
    at eval (webpack-internal:///./node_modules/@appbaseio/reactivesearch/lib/components/list/ToggleButton.js:403:60)
    at Connect (webpack-internal:///./node_modules/react-redux/es/components/connectAdvanced.js:159:37)
    at ComponentWrapper (webpack-internal:///./node_modules/@appbaseio/reactivesearch/lib/components/basic/ComponentWrapper.js:47:3)
    at Connect (webpack-internal:///./node_modules/react-redux/es/components/connectAdvanced.js:159:37)
    at PreferencesConsumer (webpack-internal:///./node_modules/@appbaseio/reactivesearch/lib/components/basic/PreferencesConsumer.js:25:22)
    at ToggleButton
```

**Comment by siddharthlatest** [comment]
@stonesthatwhisper Can you share a CodeSandbox?

This should be fixed in the latest version of ReactiveSearch.

**Comment by mohdashraf010897** [comment]
@stonesthatwhisper The issue has been addressed in [this commit](https://github.com/appbaseio/reactivesearch/commit/fde7f4d9d06eb8e352e5543322d5bb60309c40e2) and is live in new versions of the lib.
