### ISSUE TITLE
window is not defined (leaflet)

### ISSUE THREAD

**Issue by ilostit** [appbaseio/reactivesearch#872]
Hi,

i have this issue after update reactivemaps "@appbaseio/reactivesearch": "^3.0.0-beta.9"

XXX/node_modules/leaflet/dist/leaflet-src.js:7
        typeof exports === 'object' && typeof module !== 'undefined' ? factory(exports) :
                                                                ^
ReferenceError: window is not defined
    at XXX/node_modules/leaflet/src/core/Util.js:217:24
    at version (XXX/node_modules/leaflet/dist/leaflet-src.js:7:65)
    at Object.<anonymous> (XXX/node_modules/leaflet/dist/leaflet-src.js:10:2)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)

any idea ?

**Comment by metagrover** [comment]
Can you share a codesandbox replicating this issue?

**Comment by ilostit** [comment]
i will do that, but sorry it's reactiveMaps update not reactiveSearch

**Comment by metagrover** [comment]
We manage the current version reactivemaps here in this (mono-)repository.

**Comment by metagrover** [comment]
I'm able to replicate this. Are you running your app in a SSR setup?

**Comment by ilostit** [comment]
yes that's true :) thanks for your work !!!

**Comment by metagrover** [comment]
Fixed here: 8a44613 🎉 

We will roll out a release with this update including some other SSR and rendering prop upgrades shortly.
