### ISSUE TITLE
Incorrect dependency path is breaking the build (webpack + react)

### ISSUE THREAD

**Issue by ebytton** [appbaseio/reactivesearch#933]
**Bug**
Incorrect dependency path in the reactivesearch source is breaking the build (webpack + react)

**Platform:**
OSX Mojave

**Description:**
Our project build is failing because require('../../../package.json') does not exist. The correct path is require('../../../../../../package.json').version.

https://github.com/appbaseio/reactivesearch/blob/323fc25bc51f8b9d7f5c1443426d7eb26ad38ce3/packages/web/src/components/basic/ReactiveBase.js#L50

**Screenshots:**

**Minimal reproduction of the problem with instructions:**
This issue is reproducible only when you build the project using webpack. I was not able to reproduce this issue with the react-scripts

**Reactivesearch version:
"react": "^16.3.2",

**Browser:**

**Anything else:**
```
ERROR in ./~/@appbaseio/reactivesearch/package.json
Module parse failed: ~/Documents/Projects/ui/node_modules/@appbaseio/reactivesearch/package.json Unexpected token (2:9)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (2:9)
    at Parser.pp$4.raise (~/Documents/Projects/ui/node_modules/webpack/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (~/Documents/Projects/ui/node_modules/webpack/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp.semicolon (~/Documents/Projects/ui/node_modules/webpack/node_modules/acorn/dist/acorn.js:581:61)
    at Parser.pp$1.parseExpressionStatement (~/Documents/Projects/ui/node_modules/webpack/node_modules/acorn/dist/acorn.js:966:10)
    at Parser.pp$1.parseStatement (~/Documents/Projects/ui/node_modules/webpack/node_modules/acorn/dist/acorn.js:730:24)
    at Parser.pp$1.parseBlock (~/Documents/Projects/ui/node_modules/webpack/node_modules/acorn/dist/acorn.js:981:25)
    at Parser.pp$1.parseStatement (~/Documents/Projects/ui/node_modules/webpack/node_modules/acorn/dist/acorn.js:709:33)
    at Parser.pp$1.parseTopLevel (~/Documents/Projects/ui/node_modules/webpack/node_modules/acorn/dist/acorn.js:638:25)
    at Parser.parse (~/Documents/Projects/ui/node_modules/webpack/node_modules/acorn/dist/acorn.js:516:17)
    at Object.parse (~/Documents/Projects/ui/node_modules/webpack/node_modules/acorn/dist/acorn.js:3098:39)
 @ ./~/@appbaseio/reactivesearch/lib/components/basic/ReactiveBase.js 86:102-134
```

**Comment by lakhansamani** [comment]
@ebytton I tried creating minimal example using `react: 16.3.2`, `webpack-4`, `babel-7` and `@appbaseio/reactivesearch-3.0.0-rc.0`. But couldn't replicate above issue.

Here is sample code base
https://github.com/lakhansamani/reactivesearch-non-cra-example

Seems, `js` or `jsx` loader is missing in your `webpack` config, can you please check that once. 

For more information you can check https://github.com/lakhansamani/reactivesearch-non-cra-example/blob/master/webpack.config.js

**Comment by ebytton** [comment]
Hi @lakhansamani, Thanks for your prompt response. I have js and jsx loaders defined in my webpack config:

```
module.exports = {
  entry: [path.resolve(__dirname, 'app/index.js')],
  output: {
    path: '/dist',
    publicPath: '/',
    filename: '[name].bundle.js',
    chunkFilename: '[id].bundle.js',
  },
  devTool: 'eval-source-map',

  resolve: {
    extensions: ['', '.js', '.jsx', '.json'],
  },
  module: {
    preLoaders: [
      { test: /\.json$/, exclude: /node_modules/, loader: 'json' },
    ],
    loaders: [
      {
        test: [/\.jsx$/, /\.js$/],
        exclude: /node_modules/,
        loaders: ['babel'],
      },
      {
        test: /\.scss$/,
        exclude: /node_modules/,
        loaders: ['style', 'css', 'sass'],
      },
      {
        test: /\.css$/,
        loader: 'style-loader!css-loader',
      },
    ],
  },
  sassLoader: {
    includePaths: [path.resolve(__dirname, './app/css/*.scss')],
  },
  plugins: [
    new webpack.DefinePlugin({
      __COMMIT_HASH__: JSON.stringify(process.env.GIT_COMMIT),
    }),
  ],
  watchOptions: {
    aggregateTimeout: 300,
    poll: 1000
  },
};
```

"react": "^16.3.2" 
"babel-core": "6.17.0",
"webpack": "^1.15.0",
